[package]
name = "game-2048"
version = "0.1.0"
authors = ["Paul Tilley <ptilley1@binghamton.edu>"]

[dependencies]
lazy_static = "1.2.0"
rand = "0.6.1"

[dependencies.sdl2]
version = "0.31.0"
default-features = false
features = ["image", "ttf"]
